- name: FrontendSetUp
  hosts: all
  become: yes
  tasks:
    - name: Install Mysql server
      ansible.builtin.dnf:
        name: install mysql
        state: installed
    - name: Start mysql server
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enable: yes
    - name: mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenceApp@1